config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :groups
  resources :concerts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :group

  def group_name
    group.name
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :concerts, dependent: :destroy
  enum group_type: %w[BoyBand GirlBand Solo Band]

  def concerts_amount
    concerts.count
  end

  def total_attendance
    Group.includes(:concerts).references(:concerts).where(concerts: { group_id: id }).sum(:attendance)
  end

  def concerts_this_month
    arr = concerts.map(&:date)
    arr.select{ |reg| reg.to_date >= Date.today.beginning_of_month && reg.to_date <= Date.today.end_of_month }.count
  end

  def last_concert
    concerts.maximum(:date)
  end

  def max_attendance
    concerts.maximum(:attendance)
  end

  def max_duration
    concerts.maximum(:duration)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[show edit update destroy]
  def new
    @groups = Group.all
    @concert = Concert.new
  end

  def create
    @concert = Concert.new(concert_params)
    if @concert.save
      redirect_to @concert
    else
      render :new
    end
  end

  def show
  end

  def edit
    @groups = Group.all
  end

  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to concert_path(@concert), notice: 'Concert was successfully updated.'   }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect to concerts_path, notice: 'Concert was successfully deleted' }
    end
  end

  def index
    @concerts = Concert.all
  end

  private
  def concert_params
    params.require(:concert).permit(:date, :group_id, :attendance, :duration)
  end

  def set_concert
    @concert = Concert.find(params[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to @group
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_path(@group), notice: 'Band was successfully updated.'   }
      else
        format.html { render :edit }
      end
    end

  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_path, notice: 'Band was successfully deleted' }
    end

  end

  def index
    @groups = Group.all
  end

  private
  def group_params
    params.require(:group).permit(:name, :members, :debut_date, :group_type)
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/concerts/_form.html.erb
<%= form_with(model: concert, local: true) do |form| %>
<% if concert.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(concert.errors.count, "error") %> prohibited this concert from being
    saved:
  </h2>

  <ul>
    <% concert.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :group_id %> 
  <%= form.select :group_id, options_from_collection_for_select(@groups, :id, :name), prompt: 'Select a group..' %>
</div>

<div class="field">
  <%= form.label :date %> 
  <%= form.datetime_select :date %>
</div>

<div class="field">
  <%= form.label :attendance %> 
  <%= form.number_field :attendance %>
</div>

<div class="field">
  <%= form.label :duration %> 
  <%= form.number_field :duration %>
</div>


<div class="actions"><%= form.submit %></div>
<% end %>

app/views/concerts/edit.html.erb
<div class="container"><h1> Edit a concert </h1>
  <%= render 'form', concert: @concert %>

  
<p><%= link_to 'Back', concerts_path %></p>
</div>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Band</th>
      <th>Attendance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.date %></td>
        <td><%= concert.group_name %></td>
        <td><%= concert.attendance %> people</td>
        <td><%= link_to 'Details', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Delete', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'New Concert', new_concert_path %></p>
<p><%= link_to 'Bands', groups_path %></p>

app/views/concerts/new.html.erb
<div class="container"><h1> Create a concert </h1>
  <%= render 'form', concert: @concert %>

  
<p><%= link_to 'Back', concerts_path %></p>
</div>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>



<table class="table col-4">
  
  <tbody>
    <tr>
      <td><strong>Concert Date:</strong></td>
      <td><%= @concert.date %></td>
    </tr>
    <tr>
      <td><strong>Band:</strong></td>
      <td><%= @concert.group_name %></td>
    </tr>
    <tr>
      <td><strong>Attendance:</strong></td>
      <td><%= @concert.attendance %> people </td>
    </tr>
    <tr>
      <td><strong>Duration:</strong></td>
      <td><%= @concert.duration %> minutes</td>
    </tr>
  </tbody>
</table>

<p><%= link_to 'Back', concerts_path %></p>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
<% if group.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(group.errors.count, "error") %> prohibited this group from being
    saved:
  </h2>

  <ul>
    <% group.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :name %> 
  <%= form.text_field :name %>
</div>

<div class="field form-group">
  <%= form.label :members %>
  <%= form.number_field :members %>

  <div class="field">
    <%= form.label :debut_date %> 
    <%= form.datetime_select :debut_date %>
  </div>
</div>

<div class="field">
  <%= form.label :group_type %> 
  <%= form.select :group_type, %w[BoyBand GirlBand Solo Band], prompt: 'Select a group..' %>
</div>


<div class="actions"><%= form.submit %></div>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Band</h1>

<%= render 'form', group: @group %>

  
<p><%= link_to 'Back', groups_path %></p>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bands</h1>

<table class="table">
  <thead>
    <tr>
      <th>Band Name</th>
      <th>Number of Members</th>
      <th>Debut Date</th>
      <th>Composition</th>
      <th>Amount of Concerts</th>
      <th>Total Attendees</th>
      <th>Attendance by Concert</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.members %></td>
        <td><%= group.debut_date %></td>
        <td><%= group.group_type %></td>
        <td><%= group.concerts_amount %></td>
        <td><%= group.total_attendance %></td>
        <td><%= group.concerts.pluck(:attendance).join(' - ') %></td>
        <td><%= link_to 'Details', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'New Band', new_group_path %></p>
<p><%= link_to 'Concerts', concerts_path %></p>

app/views/groups/new.html.erb
<div class="container"><h1> Create a Band </h1>
  <%= render 'form', group: @group %>
</div>
  
<p><%= link_to 'Back', groups_path %></p>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>



<table class="table col-6">
  
  <tbody>
    <tr>
      <td><strong>Band:</strong></td>
      <td><%= @group.name %></td>
    </tr>
    <tr>
      <td><strong>Members:</strong></td>
      <td><%= @group.members %></td>
    </tr>
    <tr>
      <td><strong>Debut Date:</strong></td>
      <td><%= @group.debut_date %></td>
    </tr>
    <tr>
      <td><strong>Group Composition:</strong></td>
      <td><%= @group.group_type%></td>
    </tr>
    <tr>
      <td><strong>Amount of Concerts</strong></td>
      <td> <%= @group.concerts_amount %> </td>
    </tr>
    <tr>
      <td><strong>Total Attendees</strong></td>
      <td> <%= @group.total_attendance %> people </td>
    </tr>
    <tr>
      <td><strong>Concerts This Month:</strong></td>
      <td><%= @group.concerts_this_month %></td>
    </tr>
    <tr>
      <td><strong>Last Concert:</strong></td>
      <% if @group.last_concert != nil  %>
        <td><%= @group.last_concert.strftime('%Y - %B - %A %d') %></td>
      <%else  %>
        <td> No ha hecho conciertos </td>
      <%end  %>
    </tr>
    <tr>
      <td><strong>Maximum Attendees</strong></td>
      <td> <%= @group.max_attendance %> people </td>
    </tr>

    <tr>
      <td><strong>Maximum Concert Duration</strong></td>
      <td> <%= @group.max_duration %> minutes</td>
    </tr>

    

  </tbody>
</table>

<p><%= link_to 'Back', groups_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManager</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>